### ISSUE TITLE
[changemetrics.io] Add vision and blog post for version 1.0 roadmap

### ISSUE THREAD

**Issue by morucci** [change-metrics/monocle#457] opened 2021-07-07 13:32 UTC
- Import content from monocle README.
- Socialize the roadmap for the version 1.0.

**Comment by TristanCacqueray** [comment] 2021-07-07 13:55
Duplicate of https://github.com/change-metrics/changemetrics.io/issues/3

**Closed by TristanCacqueray** 2021-07-07 13:55 UTC
